apiVersion: v2
name: dits
description: Helm chart for the Dits version control system
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - dits
  - version-control
  - video
  - large-files
home: https://dits.io
sources:
  - https://github.com/dits-io/dits
maintainers:
  - name: Dits Team
    email: team@dits.io
dependencies:
  - name: postgresql
    version: "13.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "18.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
