# Dits Rust Formatting Configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
use_small_heuristics = "Max"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments and documentation
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
normalize_comments = true
normalize_doc_attributes = true

# Functions and control flow
fn_args_layout = "Tall"
fn_single_line = false
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"

# Structs and enums
struct_lit_single_line = true
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

# Chains and expressions
chain_width = 60
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50

# Macros
format_macro_matchers = true
format_macro_bodies = true

# Strings
format_strings = true

# Other
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true
force_multiline_blocks = false
