{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dits.fullname" . }}-api
  labels:
    {{- include "dits.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "dits.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
